
insert into clientes (id,nombre,apellido,email,create_at,foto) values (1,'Cliente1','apellido1','email1@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (2,'Cliente2','apellido2','email2@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (3,'Cliente3','apellido2','email2@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (4,'Cliente4','apellido2','email2@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (5,'Cliente5','apellido2','email2@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (6,'Cliente6','apellido2','email2@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (7,'Cliente7','apellido2','email2@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (8,'Cliente8','apellido2','email2@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (9,'Cliente9','apellido2','email2@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (10,'Cliente10','apellido2','email2@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (11,'Cliente11','apellido2','email2@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (12,'Cliente12','apellido2','email2@gmail.com','2021-01-02',"")
insert into clientes (id,nombre,apellido,email,create_at,foto) values (13,'Cliente13','apellido2','email2@gmail.com','2021-01-02',"")
